import { describe, expect, it } from "vitest";
import { renderAnchorStarter } from "./anchor-starter.js";

describe("renderAnchorStarter", () => {
  it("renders the heading, identity line, commit-routing, and per-repo pointers", () => {
    const doc = renderAnchorStarter({
      anchorName: "acme-planning",
      viewName: "acme-workspace",
      repos: [{ name: "acme-planning", anchor: true }, { name: "acme" }, { name: "acme-beta" }],
    });
    expect(doc).toContain("# AGENTS.md (acme-planning)");
    // Identity falls back to the anchor name when no project name is declared.
    expect(doc).toContain("**planning master (anchor) of acme-planning**");
    // Commit-routing is prose, not a per-repo table.
    expect(doc).toContain("## Where to commit");
    expect(doc).toContain("**This repository (the planning master)**");
    // Per-repo pointers exclude the anchor (that IS this file).
    expect(doc).toContain("- acme/AGENTS.md");
    expect(doc).toContain("- acme-beta/AGENTS.md");
    expect(doc).not.toContain("- acme-planning/AGENTS.md");
  });

  it("does NOT snapshot a roster table into the frozen file (points at the view for the live roster)", () => {
    const doc = renderAnchorStarter({
      anchorName: "acme-planning",
      viewName: "acme-workspace",
      repos: [{ name: "acme-planning", anchor: true }, { name: "acme" }],
    });
    // No manifest-derived roster snapshot table (it would drift silently in a
    // markerless, never-resynced file).
    expect(doc).not.toContain("| repo | visibility | language | instructions |");
    expect(doc).not.toContain("snapshot");
    // Instead, the view's generated AGENTS.md is the live-roster source of truth.
    expect(doc).toContain(
      "- acme-workspace/AGENTS.md (the workspace view, generated by basou) — **the authoritative, up-to-date repo roster (the live roster) lives there**",
    );
  });

  it("declares itself a create-only, marker-less starter that basou never rewrites", () => {
    const doc = renderAnchorStarter({ anchorName: "p", repos: [{ name: "p", anchor: true }] });
    expect(doc).toContain("generated **once** at greenfield bring-up");
    expect(doc).toContain("basou never regenerates or overwrites it");
    // It must NOT carry BASOU:GENERATED markers — it is hand-maintained, not synced.
    expect(doc).not.toContain("BASOU:GENERATED:START");
    expect(doc).not.toContain("BASOU:GENERATED:END");
  });

  it("uses the declared project name in the identity line and info block when present", () => {
    const doc = renderAnchorStarter({
      anchorName: "acme-planning",
      projectName: "Acme",
      repos: [{ name: "acme-planning", anchor: true }],
    });
    expect(doc).toContain("**planning master (anchor) of Acme**");
    expect(doc).toContain("Product name:          Acme");
  });

  it("leaves undeclarable product facts as TODO stubs", () => {
    const doc = renderAnchorStarter({ anchorName: "p", repos: [{ name: "p", anchor: true }] });
    // No project name declared => the product-name field is a TODO too.
    expect(doc).toContain("Product name:          <!-- TODO -->");
    expect(doc).toContain("Domain:                <!-- TODO -->");
    expect(doc).toContain("GitHub Organization:   <!-- TODO -->");
    expect(doc).toContain("License:               <!-- TODO -->");
    // Project-specific policy is left for the operator to fill.
    expect(doc).toContain("## Working policy (project specifics)");
    expect(doc).toContain("Language policy");
  });

  it("omits the view pointer when the project has no workspace view", () => {
    const doc = renderAnchorStarter({
      anchorName: "solo-planning",
      repos: [{ name: "solo-planning", anchor: true }, { name: "solo" }],
    });
    expect(doc).toContain("- solo/AGENTS.md");
    expect(doc).not.toContain("the workspace view, generated by basou");
  });

  it("is deterministic (byte-identical) for the same input and ends with a newline", () => {
    const input = {
      anchorName: "acme-planning",
      viewName: "acme-workspace",
      repos: [{ name: "acme-planning", anchor: true }, { name: "acme" }],
    };
    expect(renderAnchorStarter(input)).toBe(renderAnchorStarter(input));
    expect(renderAnchorStarter(input).endsWith("\n")).toBe(true);
  });

  it("renders the Japanese starter when the anchor declares language: ja", () => {
    const doc = renderAnchorStarter({
      anchorName: "acme-planning",
      viewName: "acme-workspace",
      repos: [{ name: "acme-planning", anchor: true, language: "ja" }, { name: "acme" }],
    });
    expect(doc).toContain("**acme-planning の planning master(anchor)**");
    expect(doc).toContain("## どこで commit するか");
    expect(doc).toContain(
      "- acme-workspace/AGENTS.md(workspace view・basou が生成)— **最新の repo 構成(roster)はここを正とする**",
    );
  });

  it("only the ANCHOR entry's language participates (a ja member repo does not flip the starter)", () => {
    const doc = renderAnchorStarter({
      anchorName: "acme-planning",
      repos: [
        { name: "acme-planning", anchor: true, language: "en" },
        { name: "acme", language: "ja" },
      ],
    });
    expect(doc).toContain("## Where to commit");
    expect(doc).not.toContain("どこで commit するか");
  });

  // Golden full-file lock on the ja bytes: a ja anchor promises the exact
  // pre-i18n starter, so any edit to the ja table (or to how the generator
  // assembles it) must surface here as a full-file diff.
  it("golden: a ja anchor renders this exact starter", () => {
    const doc = renderAnchorStarter({
      anchorName: "acme-planning",
      projectName: "Acme",
      viewName: "acme-workspace",
      repos: [
        { name: "acme-planning", anchor: true, language: "ja" },
        { name: "acme" },
        { name: "acme-site" },
      ],
    });
    expect(doc).toBe(JA_GOLDEN_STARTER);
  });
});

const JA_GOLDEN_STARTER = `${[
  "# AGENTS.md (acme-planning)",
  "",
  "> このリポジトリは **Acme の planning master(anchor)** です。ここで作業する AI エージェントは、まずこのファイルを読んでください。",
  ">",
  "> このファイルは `basou project derive` が greenfield 立ち上げ時に **一度だけ生成した starter** です。以後は手管理してください — basou は再生成も上書きもしません(BASOU:GENERATED マーカーは無く、自由に編集できます)。",
  "",
  "## プロジェクトの基本情報",
  "",
  "<!-- TODO: manifest からは導出できない項目です。埋めてください。 -->",
  "",
  "```text",
  "Product name:          Acme",
  "Domain:                <!-- TODO -->",
  "GitHub Organization:   <!-- TODO -->",
  "Public repository:     <!-- TODO -->",
  "Planning repository:   <!-- TODO -->",
  "License:               <!-- TODO -->",
  "```",
  "",
  "## どこで commit するか",
  "",
  "- **このリポジトリ(planning master)**: 構想・計画・設計ドキュメント。",
  "- **各実装 repo**: 実装コード。必ず対象 repo に `cd` してから commit してください。",
  "- **workspace view**: git 管理外。view では commit できません。",
  "",
  "## 必ず読むべき規約",
  "",
  "作業規約は各 repo の AGENTS.md にあります。以下を読んでから作業してください。",
  "",
  "- acme/AGENTS.md",
  "- acme-site/AGENTS.md",
  "- acme-workspace/AGENTS.md(workspace view・basou が生成)— **最新の repo 構成(roster)はここを正とする**",
  "",
  "## 作業方針(プロジェクト固有事項)",
  "",
  "<!-- TODO: 以下をプロジェクトに合わせて記述してください。",
  "  - 現在のフェーズ / 重要ドキュメント",
  "  - 機密情報の扱い(どこに書かないか)",
  "  - 言語ポリシー(commit / コメント / ドキュメントの言語)",
  "  - commit 運用(混在コミットを避ける 等)",
  "-->",
].join("\n")}\n`;
